name: Deploy WordPress Version

on:
  push:
    branches:
      - main

env:
  TF_VERSION: '1.10.4'
  AWS_REGION: 'eu-south-1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
#          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 900
          role-skip-session-tagging: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Extract version from tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "TF_VAR_wordpress_version=${TAG_VERSION}"
          echo "TF_VAR_wordpress_version=${TAG_VERSION}" >> $GITHUB_ENV

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
            -backend-config="key=wordpress" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Apply (main branch only)
        if: github.ref == 'refs/heads/main'
        run: terraform apply --target=aws_ecs_service.wordpress --auto-approve